### PR TITLE
fix sonar-scanner import error when empty line

### PR DESCRIPTION
**Pull request by aglensmith**
## Proposed changes

This applies [Turiok](https://github.com/Turiok)'s PR [sonar-scanner import error when empty line](https://github.com/omegacen/pylint-sonarjson/pull/8) made to [omegacen/pylint-sonarjson](https://github.com/omegacen/pylint-sonarjson).

SonarScanner does not expect startColumn to be included in the report JSON for issues on empty lines because empty lines do not have columns. With this change, startColumn is omitted if the message column is not greater than 0.

More context here: https://sonarsource.atlassian.net/browse/SONAR-20958

## Types of changes

What types of changes does your code introduce to this project?
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Issues closed by changes

- [x] Close [#7 from parent repo](https://github.com/omegacen/pylint-sonarjson/issues/7#issuecomment-1398138154)

### CODE REVIEW

**Review by tbutler-qontigo — APPROVED** [review]

**Comment by tbutler-qontigo** [comment]
@louisjdmartin could this be applied and released?  We had to stop using the plugin because Sonar won't fix the issue on their end and this is happening for us.
thanks

**Review by louisjdmartin — CHANGES_REQUESTED** [review]
Ok for approving this PR, but before, can you edit setup.py to upgrade version to 2.0.1 ?

**Comment by tbutler-qontigo** [comment]
> Ok for approving this PR, but before, can you edit setup.py to upgrade version to 2.0.1 ?

@aglensmith Can you make this change since the PR is from your fork?  Thanks

**Comment by aglensmith** [comment]
@tbutler-qontigo @louisjdmartin I've updated the version to `2.0.1` as requested

**Review by louisjdmartin — APPROVED** [review]

**Comment by tbutler-qontigo** [comment]
@louisjdmartin Could you publish this version to pypi,org?  It still only has 2.0.0 as the latest version.

**Comment by louisjdmartin** [comment]
It's already published, we reused original repo name (the "-catlab" was before we get write permissions)

https://pypi.org/project/pylint-sonarjson/

I'm going to fix readme soon

**Pull request merged**
